name: RealDice
version: 1.0.0
author: 202e
main: io.github._202e.realdice.RealDice
api-version: 1.14
commands:
  roll:
    permission: realdice.roll
    description: Rolls dice based on a formula like 1d20+3d6-10
    usage: "§c/<command> <formula>"